import { Inter } from "next/font/google";
import "./globals.css";
import LayoutManager from "./components/LayoutManager";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Acme Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Oxygen:wght@300;400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <LayoutManager>
          <main className="bg-[#171717] text-white ">{children}</main>
        </LayoutManager>
      </body>
    </html>
  );
}
